session_name: dev
windows:
  - window_name: editor
    focus: true
    panes:
      - shell_command:
          - nvim
  - window_name: server
    panes:
      - shell_command:
          - clear
  - window_name: terminal
    panes:
      - shell_command:
          - clear
